/*
 * +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * | ClassName.cpp
 * +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * | project   projectName
 * +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * | authors   
 * |           Name                 Email
 * +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

#include "ClassName.h"


namespace moca {

/* ClassName definition */

ClassName::ClassName() {
	// TODO autogenerated
}

ClassName::ClassName(const ClassName& toCopy) {
	// TODO autogenerated
}

virtual ClassName::~ClassName() { }


} /* namespace moca */

#endif /* CLASSNAME_H_ */

